version: "3"
services:
  users:
    build: ./users/
    ports:
        - "8080:80"
    environment:
        ASPNETCORE_ENVIRONMENT: "Development"
  posts:
    build: ./posts/
    ports:
        - "8081:80"
    environment:
        ASPNETCORE_ENVIRONMENT: "Development"
  comments:
    build: ./comments/
    ports:
        - "8082:80"
    environment:
        ASPNETCORE_ENVIRONMENT: "Development"
